name: Titan Python Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install instagrapi

      - name: Run Titan Engine
        env:
          INSTA_SESSION_ID: ${{ secrets.INSTA_SESSION_ID }}
          MESSAGES: ${{ secrets.MESSAGES }}
        run: python praveer_v109s.py
